@startuml callback_message

(*) --> "服务启动"
--> "收到微信后台推送的 xml"
--> "解析 xml 数据"
--> "尝试提取出 signature, timestamp, nonce, encrypt_type 参数"
if "字段提取成功" then
  -->[Y] "提取加密传输标识"
  if "加密传输" then
    -->[Y] "根据配置校验参数合法性"
    if "参数校验成功" then
      -->[Y] "确认是微信后台的请求"
      --> "解析加密后的 xml"
      --> "消息类型提取"
    else
      -->[N] "不是微信后台的请求"
    endif
  else
    -->[N] "消息类型提取"
  endif
  --> "根据具体需求组织响应信息"
  --> "生成响应消息 xml"
  --> "返回给微信后台"
  -->(*)
else
  -->[N] "不是微信后台的请求"
  --> 返回空字符串
  -->(*)
endif

@enduml